ALTER TABLE figures ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE figures ADD COLUMN IF NOT EXISTS material TEXT;
ALTER TABLE figures ADD COLUMN IF NOT EXISTS order_date TEXT;
ALTER TABLE figures ADD COLUMN IF NOT EXISTS shipping_date TEXT;
